apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product
  # namespace: ecommerce
spec:
  ports:
  - nodePort: 32702
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: product
  sessionAffinity: None
  type: NodePort